[package]
name = "agui"
version = "0.2.0"
edition = "2021"
resolver = "2"
description = "A reactive GUI project"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = [ "gui", "graphics", "gamedev" ]
categories = [ "gui", "graphics", "rendering", "game-development" ]
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace]
members = [
    "agui_core",
    "agui_macros",
    "agui_primitives",
    "agui_widgets",
    "agui_agpu"
]

[features]
default = [ "primitives", "widgets", "macros" ]
primitives = [ "agui_primitives" ]
widgets = [ "primitives", "agui_widgets" ]
macros = [ "agui_macros" ]

[dependencies]
agui_core = { path = "agui_core", version = "0.2" }
agui_macros = { path = "agui_macros", version = "0.2", optional = true }
agui_primitives = { path = "agui_primitives", version = "0.2", optional = true }
agui_widgets = { path = "agui_widgets", version = "0.2", optional = true }