[package]
name = "agui_core"
version = "0.3.0"
edition = "2021"
resolver = "2"
description = "The core library of agui"
homepage = "https://github.com/Stumblinbear/agui"
repository = "https://github.com/Stumblinbear/agui"
keywords = ["gui", "gamedev"]
categories = ["gui", "game-development"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
cfg-if = "1.0"

tracing.workspace = true

thiserror.workspace = true

rand.workspace = true
rustc-hash.workspace = true
slotmap.workspace = true
parking_lot.workspace = true
im-rc.workspace = true

lyon.workspace = true

[dev-dependencies]
agui_macros.workspace = true
